name: fcommerce
description: f-commerce by Iandi Santulus

publish_to: 'none'
version: 0.0.0+2

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  geocoding: ^2.0.0
  get_it: ^7.2.0
  http: ^0.13.3
  intl: ^0.17.0
  location: ^4.3.0
  retry: ^3.1.0
  rxdart: ^0.27.1
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.5.3

flutter:

  uses-material-design: true
