name: fcommerce
description: f-commerce by Iandi Santulus

publish_to: 'none'
version: 0.0.1+4

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  equatable: ^2.0.3
  firebase_core: ^1.8.0
  firebase_messaging: ^10.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.1
  flutter_local_notifications: ^9.0.0
  geocoding: ^2.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  intl: ^0.17.0
  location: ^4.3.0
  retry: ^3.1.0
  rxdart: ^0.27.2
  shimmer: ^2.0.0
  sqflite: ^2.0.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.5.3

flutter:

  uses-material-design: true

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
